apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: REPLACED_BY_JENKINS
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /nifi/, port: 8080 }
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /nifi/, port: 8080 }
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1",    memory: "1Gi" }
